#!/usr/bin/env bash
# core/ -> .claude/agents/. Claude Code discovers agents by path convention
# (.claude/agents/*.md), so the sources in core/ can't just live where the
# runtime expects them — this script is the compose step in between.
#
# Generated files are committed (not gitignored): Claude Code needs to find
# them on a fresh clone with no build step, and a generated prompt's diff is
# the most reviewable artifact this repo produces — it shows exactly what
# changed in the instruction, which is the thing that changes behaviour.
# Never hand-edit a file under .claude/agents/ — re-run this instead.
set -eu
ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"
mkdir -p .claude/agents

BANNER="# GENERATED by harness/build-agents.sh from core/ — edit core/, not this file."

# ---- scout: verbatim copy, no templating (no shared doctrine to extract —
# it doesn't follow the Job 1/Job 2 verifier shape) ----
{
  head -1 core/agents/scout.md          # the opening "---"
  echo "$BANNER"
  tail -n +2 core/agents/scout.md       # everything else, unchanged
} > .claude/agents/pr-review-scout.md

# ---- each verify-*.body.md, composed with core/doctrine.md ----
for body in core/agents/verify-*.body.md; do
  [ -e "$body" ] || continue
  slug="$(basename "$body" .body.md)"   # e.g. verify-access
  python3 harness/compose-verifier.py "$body" core/doctrine.md "$BANNER" \
    > ".claude/agents/pr-${slug}.md"
done

echo "built: $(ls .claude/agents/*.md | wc -l | tr -d ' ') agent(s) in .claude/agents/"
