#!/usr/bin/env bash
# core/ -> .claude/agents/. Claude Code discovers agents by path convention
# (.claude/agents/*.md), so the sources in core/ can't just live where the
# runtime expects them — this script is the compose step in between.
#
# Generated files are committed (not gitignored): Claude Code needs to find
# them on a fresh clone with no build step, and a generated prompt's diff is
# the most reviewable artifact this repo produces — it shows exactly what
# changed in the instruction, which is the thing that changes behaviour.
# Never hand-edit a file under .claude/agents/ — re-run this instead.
set -eu
ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"
OUT_DIR="${AGENTS_OUT:-.claude/agents}"   # overridable so check-generated.sh can diff against a scratch dir without touching the real one
mkdir -p "$OUT_DIR"

BANNER="# GENERATED by harness/build-agents.sh from core/ — edit core/, not this file."

# ---- scout: verbatim copy, no templating (no shared doctrine to extract —
# it doesn't follow the Job 1/Job 2 verifier shape) ----
{
  head -1 core/agents/scout.md          # the opening "---"
  echo "$BANNER"
  tail -n +2 core/agents/scout.md       # everything else, unchanged
} > "$OUT_DIR/pr-review-scout.md"

# ---- each verify-*.body.md, composed with core/doctrine.md ----
for body in core/agents/verify-*.body.md; do
  [ -e "$body" ] || continue
  slug="$(basename "$body" .body.md)"   # e.g. verify-access
  python3 harness/compose-verifier.py "$body" core/doctrine.md "$BANNER" \
    > "$OUT_DIR/pr-${slug}.md"
done

# find + wc -l, not `ls ... | wc -l` — ls fails (invisibly to set -e, buried
# inside a command substitution) when $OUT_DIR ends up empty, which used to
# silently print "built: 0 agent(s)" as if that were success. wc -l always
# exits 0 even on empty input, unlike `grep -c .` which would exit 1 here
# and abort under set -e before the explicit check below ever ran.
COUNT="$(find "$OUT_DIR" -maxdepth 1 -name '*.md' | wc -l | tr -d ' ')"
[ "$COUNT" -gt 0 ] || { echo "error: 0 agent files written to $OUT_DIR — nothing to build?" >&2; exit 1; }
echo "built: $COUNT agent(s) in $OUT_DIR"
